### PR TITLE
fix #387

### LINKED ISSUE #387: Authentication doesn't work with CouchDB if option require_valid_user is enabled
I want to connect to a CouchDB instance (example code below) with the configuration parameter
```
require_valid_user = true
```
this gives a 
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:5984/_session
```
A hot fix for cookie based authentication would be:
```
diff --git a/src/cloudant/_client_session.py b/src/cloudant/_client_session.py
index 0e8fd38..d608f8e 100644
--- a/src/cloudant/_client_session.py
+++ b/src/cloudant/_client_session.py
@@ -148,6 +148,7 @@ class CookieSession(ClientSession):
             'POST',
             self._session_url,
             data={'name': self._username, 'password': self._password},
+            auth=(self._username, self._password)
         )
         resp.raise_for_status()
```

- Cloudant (python-cloudant) version(s) that are affected by this issue.
```
$ pip list | grep cloudant
cloudant (2.8.1)
```
- Python version 
```
$ python --version
Python 3.6.5
```
- A small code sample that demonstrates the issue.
```
# This works
import requests
import json
auth = ('admin', '31sf13b3r!')
get_url = "http://127.0.0.1:5984/_session".format(auth[0])
r = requests.get(get_url, auth=auth)
print(json.dumps(r.json(), indent=1))


# This doesn't work
from cloudant import CouchDB
db = CouchDB(*auth, url='http://127.0.0.1:5984')
db.connect()
print(db.all_dbs())
```

### PR DESCRIPTION
**Pull request by schferbe**
## Checklist

- [X ] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [X] Added tests for code changes _or_ test/build only changes
- [X] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [X] Completed the PR template below:

## Description

Fixes #387 

## Approach
added auth parameters to login request

## Schema & API Changes
No change

## Security and Privacy
No change

## Testing

No new tests because specific CouchDB configuration would be needed. 

## Monitoring and Logging

No change

### CODE REVIEW

**Comment by ricellis** [comment]
Just an FYI that this problem was [recently corrected for CouchDB 3](https://github.com/apache/couchdb/pull/2321), so should be going away server-side from that release.

**Comment by schferbe** [comment]
Thank you! That is good to know. CouchDB doesn't seem to release on a weekly base though so it might be nice to have it here as well.

**Comment by bessbd** [comment]
Hi @schferbe ,
Thank you for the patch! For us to merge this change, we’d need more tests so that we can be confident it does not break other things accidentally and that this would not get removed accidentally.
Looking at https://lists.apache.org/thread.html/5c81b88c60ce81506d650893c61cd9228f4c1c0fab777e55a4f5c27a@%3Cdev.couchdb.apache.org%3E , it seems couchdb3 is very close to a release.
Can you wait until couchdb3 is released or would you like to put more efforts into having automated tests for this change?

Also, have you tried using basic auth when `require_valid_user` is enabled as a workaround?

**Comment by schferbe** [comment]
Now CouchDB 3 is released in their own  apt repository. I will close this PR.

**Comment by vlad88sv** [comment]
I just ran into this situation, and the fix provided worked really fine!

Any chance this could still get merged? (pretty please?)

**Comment by ricellis** [comment]
You can workaround `require_valid_user` blocking the `_session` endpoint in CouchDB 2.x by making python-cloudant use basic auth instead. This is done by initializing with the `use_basic_auth=True` kwarg e.g.
```python
CouchDB(user, pass, url=url, use_basic_auth=True)
```

**Comment by vlad88sv** [comment]
Thank you! that parameter worked fine!

**Pull request closed without merging**
