### PR TITLE
Remove incorrect restriction from docs for bookmarks

### PR DESCRIPTION
**Pull request by bessbd**
## Checklist

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [x] Added tests for code changes _or_ test/build only changes
- [x] Updated the change log file (`CHANGES.md`) _or_ test/build only changes
- [x] Completed the PR template below:

## Description
The docs for `bookmarks` was incorrect. This PR fixes that.

## Schema & API Changes

- "No change"

## Security and Privacy

- "No change"

## Testing

- Docs only change

## Monitoring and Logging

- "No change"

### CODE REVIEW

**Comment by glynnbird** [comment]
:+1: LGTM

**Review by glynnbird — APPROVED** [review]
LGTM 👍  (this time as a review)

**Review by ricellis — APPROVED** [review]
+1

**Comment by bessbd** [comment]
Thank you for the review, @glynnbird and @ricellis . I'm about to merge this.

**Pull request merged**
