### PR TITLE
non-UTF8 chars (like \u2013) in your map/reduce will make the ddoc fetch puke

### PR DESCRIPTION
**Pull request by madmaze**
Thanks for your hard work, please ensure all items are complete before opening.

- [x] You have signed the CLA as per the instructions in [CONTRIBUTING.rst](https://github.com/cloudant/python-cloudant/blob/master/CONTRIBUTING.rst#contributor-license-agreement) (IBMer)
- [ ] You have added tests for any code changes
- [x] You have updated the [CHANGES.rst](https://github.com/cloudant/python-cloudant/blob/master/CHANGES.rst) 
- [x] You have completed the PR template below:

## What

What was changed, e.g. Added support for querying views.
- fixed crash on non-UTF8 chars in design docs

## How
 - fixed by encoding to UTF8

## Testing

How to test your changes work, not required for documentation changes.
Setup faulty view with `couchapp`
```bash
mkdir test
cd test
couchapp init
couchapp generate view foo
couchapp push http://admin:password@localhost:5984/foo
```

`test.py`:
```python
from cloudant import couchdb_admin_party
from cloudant.design_document import DesignDocument

with couchdb_admin_party(url="http://localhost:5984") as couch:
    db = couch.get('foo', remote=True)

    ddoc = DesignDocument(db, '_design/test')
    ddoc.fetch()
```
cause error:
```bash
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    ddoc.fetch()
  File "/usr/local/lib/python2.7/dist-packages/cloudant/design_document.py", line 491, in fetch
    **view_def
  File "/usr/local/lib/python2.7/dist-packages/cloudant/view.py", line 107, in __init__
    self['reduce'] = codify(reduce_func)
  File "/usr/local/lib/python2.7/dist-packages/cloudant/_common_util.py", line 234, in codify
    return _Code(code_or_str)
  File "/usr/local/lib/python2.7/dist-packages/cloudant/_common_util.py", line 291, in __new__
    return str.__new__(cls, code)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 341: ordinal not in range(128)
```

## Issues

Links to the github issue(s) (if present) that this pull request is resolving.

### CODE REVIEW

**Comment by madmaze** [comment]
well.. looks like I'll need to rethink that approach a little bit..

**Comment by madmaze** [comment]
better now, though I think the import error travis sees is unrelated to my changes, maybe a config issue?

**Comment by alfinkel** [comment]
Since you're an IBMer we just need an email from your manager saying that they are okay with you contributing to this repo before we can merge your PR.  Have the email sent to ricellis@uk.ibm.com, alfinkel@us.ibm.com, and mike.rhodes@uk.ibm.com.

**Comment by alfinkel** [comment]
You are correct that the import error is not your issue.  It should be resolved with https://github.com/cloudant/python-cloudant/pull/300.

**Comment by MatthiasLeeIBM** [comment]
squerging as per convo with @ricellis

**Pull request merged**
